//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneTodo.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SceneTodo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 高级搜索 的本地化字符串。
        /// </summary>
        internal static string AdvancedSearch_Button {
            get {
                return ResourceManager.GetString("AdvancedSearch_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SceneTodo 的本地化字符串。
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        internal static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        internal static string Common_Filter {
            get {
                return ResourceManager.GetString("Common_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        internal static string Filter_Button {
            get {
                return ResourceManager.GetString("Filter_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日历视图 的本地化字符串。
        /// </summary>
        internal static string Menu_CalendarView {
            get {
                return ResourceManager.GetString("Menu_CalendarView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史记录 的本地化字符串。
        /// </summary>
        internal static string Menu_History {
            get {
                return ResourceManager.GetString("Menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划任务 的本地化字符串。
        /// </summary>
        internal static string Menu_ScheduledTasks {
            get {
                return ResourceManager.GetString("Menu_ScheduledTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规视图 的本地化字符串。
        /// </summary>
        internal static string Menu_TodoListView {
            get {
                return ResourceManager.GetString("Menu_TodoListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Message_Info {
            get {
                return ResourceManager.GetString("Message_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置已保存。重启应用后生效。 的本地化字符串。
        /// </summary>
        internal static string Message_LanguageSaved {
            get {
                return ResourceManager.GetString("Message_LanguageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开语言设置 的本地化字符串。
        /// </summary>
        internal static string Message_OpenLanguageSettingsFailed {
            get {
                return ResourceManager.GetString("Message_OpenLanguageSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开设置窗口 的本地化字符串。
        /// </summary>
        internal static string Message_OpenSettingsFailed {
            get {
                return ResourceManager.GetString("Message_OpenSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string Message_SaveFailed {
            get {
                return ResourceManager.GetString("Message_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string Message_SaveSuccess {
            get {
                return ResourceManager.GetString("Message_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置已重置为默认值 的本地化字符串。
        /// </summary>
        internal static string Message_SettingsResetSuccess {
            get {
                return ResourceManager.GetString("Message_SettingsResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索待办... (Ctrl+F) 的本地化字符串。
        /// </summary>
        internal static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观设置 的本地化字符串。
        /// </summary>
        internal static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份管理 的本地化字符串。
        /// </summary>
        internal static string Settings_Backup {
            get {
                return ResourceManager.GetString("Settings_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置 的本地化字符串。
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置配置 的本地化字符串。
        /// </summary>
        internal static string Settings_ResetConfig {
            get {
                return ResourceManager.GetString("Settings_ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置数据 的本地化字符串。
        /// </summary>
        internal static string Settings_ResetData {
            get {
                return ResourceManager.GetString("Settings_ResetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题设置 (旧版) 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Old {
            get {
                return ResourceManager.GetString("Settings_Theme_Old", resourceCulture);
            }
        }
    }
}
